### ISSUE TITLE
Android - Update sample app UI

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-android#88]
Update the UI wih the design defined in #71

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/218476032-a53fbbd1-0f84-4b97-a6d0-1157ac208680.png)

**Comment by ricardobrg** [comment]
https://www.figma.com/file/SEtztgSYL3x9cQeScAwcVL/sample-apps?node-id=1%3A31&t=KZ7sIpDSuAefJNJ9-1

**Comment by sfaria27** [comment]
@mike-audi
